### ISSUE TITLE
Theme is not compatible with Thunderbird 31.4.0

### ISSUE THREAD

**Issue by Mno-hime** [gnome-integration-team/thunderbird-gnome#19]
With the update of Thunderbird to 31.4.0 the theme is no longer compatible, says Add-ons Manager.

**Comment by jurf** [comment]
Same here.

**Comment by omgmog** [comment]
It's quite simple to make it work in 31.4.0:
1. Clone the repo
2. Edit `theme/install.rdf`
3. Increase the `em:maxVersion` to `32.*`
4. Run the `make-xpi.sh`
5. Install the xpi in Thunderbird.

**Comment by Mno-hime** [comment]
That worked, thanks!

**Comment by rickysarraf** [comment]
Can this be rolled out please ? There'll be a lot of users on this version of TB as that is the ESR version. Also Debian Jessie will be shipping the same.

**Comment by ElectricPrism** [comment]
This Theme seems to work just fine on Thunderbird 31.6 Arch Linux
1. git clone https://github.com/gnome-integration-team/thunderbird-gnome.git
2. gedit ~/thunderbird-gnome/theme/install.rdf
   a. On Line 41 Find "31._" Replace With "32._"
   b. Save

3.Run "~/thunderbird-gnome/make-xpi.sh"
1. Open Thunderbird
   a. Navigate to "Tools -> Addons" and then (( Appearance Screen ))
   b. Click on the [ Gear ] icon to reveal the dropdown menu in the top right to the left of the [ Search Addons Box ]
   c. Select "Install Add-on From File"
   d. Enter the file location: ~/thunderbird-gnome/gnome-thunderbird-24.0.xpi

**Comment by enriquezneilmarvin** [comment]
where can i edit the theme/install.rdf ? thanks for your answer :)

**Comment by jurf** [comment]
Just look at @ElectricPrism's reply.
