### ISSUE TITLE
Release version compatible with 11 - 12

### ISSUE THREAD

**Issue by garrett** [gnome-integration-team/thunderbird-gnome#8]
What, in your opinion, is needed to release a new version? Should we just go with the incomplete snapshot in the WIP branch now? Or should we fix a few more things before releasing a new version (which is compatible with stable Thunderbird)? If so, what things?

WIP branch is @ https://github.com/adwaita-firefox-team/adwaita-thunderbird/tree/update-wip

**Comment by ghost** [comment]
I've been testing the latest commit in the update-wip branch with Thunderbird 11.0.1. Seems to be working very nicely - great work. I'd say you can release it as is, especially given that the version currently on the Addons site looks really bad with tbird 11.

**Comment by pulb** [comment]
I agree with thaelim here, I've already got a mozilla user comment notification regarding thunderbird 11 incompatibility.

**Comment by pulb** [comment]
Oh, and I think it's time you replace my email address with yours on the addins site ;-)

**Comment by garrett** [comment]
Sounds good. How do we go about switching it on the addons site then? (:

**Comment by pulb** [comment]
Garrett, I've send you an email.

**Comment by garrett** [comment]
Closing, as we're going to support Thunderbird 15+ instead.
